### ISSUE TITLE
Dawnload exeption in try to get file

### ISSUE THREAD

**Issue by rsereda** [carlossg/glacier-cli#15]
I uploaded to glacier with this toolssame file and now try to get one for test and got this error.

My example upload commend that end with uploaded status

And i try download any other client bot did not have sucsses.

the is my upload command

java -jar /home/sseto/glacier-cli-master/target/glacier-1.1-SNAPSHOT-jar-with-dependencies.jar  upload MWP home_upload_folder_nosymlink.tar.gz

java -jar glacier-1.1-SNAPSHOT-jar-with-dependencies.jar download MWP /home/home_upload_folder_nosymlink.tar.gz 111

Exception in thread "main" java.lang.RuntimeException: Error Downloading /home/home_upload_folder_nosymlink.tar.gz from Glacier vault MWP
        at org.csanchez.aws.glacier.Glacier.download(Glacier.java:208)
        at org.csanchez.aws.glacier.Glacier.main(Glacier.java:138)
Caused by: Status Code: 404, AWS Service: AmazonGlacier, AWS Request ID: LGTOWVgl0TOy3l_zm_ZaEcWP69zSKiFUOXJL0OZK0Dlp0tU, AWS Error Code: ResourceNotFoundException, AWS Error Message: The archive ID was not found: /home/home_upload_folder_nosymlink.tar.gz
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:610)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:310)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:164)
        at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:1949)
        at com.amazonaws.services.glacier.AmazonGlacierClient.initiateJob(AmazonGlacierClient.java:1197)
        at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.download(ArchiveTransferManager.java:329)
        at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.download(ArchiveTransferManager.java:281)
        at org.csanchez.aws.glacier.Glacier.download(Glacier.java:206)
        ... 1 more

**Comment by carlossg** [comment]
you need to use the uploaded file id in order to download it later on, not the file name

**Comment by rsereda** [comment]
I use this command 

java -jar glacier-1.1-SNAPSHOT-jar-with-dependencies.jar  download MWP 0BWBXPZ8s6wYu4gmA6exw88HXBsIaEOWPwwt4M5nN0A1k8PCBQbtcx4i7SrCUAFHG1LuNz4_dEI-XKy6YrRW6QJUqe4WW5zdRuxSfI5IeIfo4657RluhRhFt6sEQPt0RRGuK4rNMTg /home/sset/home_upload_folder_nosymlink.tar.gz

I and get this error too
Exception in thread "main" java.lang.RuntimeException: Error Downloading 0BWBXPZ8s6wYu4gmA6exw88HXBsIaEOWPwwt4M5nN0A1k8PCBQbtcx4i7SrCUAFHG1LuNz4_dEI-XKy6YrRW6QJUqe4WW5zdRuxSfI5IeIfo4657RluhRhFt6sEQPt0RRGuK4rNMTg from Glacier vault MWP
        at org.csanchez.aws.glacier.Glacier.download(Glacier.java:208)
        at org.csanchez.aws.glacier.Glacier.main(Glacier.java:138)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:571)
        at java.util.ArrayList.get(ArrayList.java:349)
        at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:134)
        at com.amazonaws.services.glacier.internal.TreeHashInputStream.getTreeHash(TreeHashInputStream.java:71)
        at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.downloadJobOutput(ArchiveTransferManager.java:376)
        at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.download(ArchiveTransferManager.java:347)
        at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.download(ArchiveTransferManager.java:281)
        at org.csanchez.aws.glacier.Glacier.download(Glacier.java:206)
        ... 1 more

The is vault inventory result

"VaultARN":"arn:aws:glacier:us-east-1:219346743369:vaults/MWP",
"InventoryDate":"2013-02-14T08:23:18Z",
"ArchiveList":[
{
"ArchiveId":"0BWBXPZ8s6wYu4gmA6exw88HXBsIaEOWPwwt4M5nN0A1k8PCBQbtcx4i7SrCUAFHG1LuNz4_dEI-XKy6YrRW6QJUqe4WW5zdRuxSfI5IeIfo4657RluhRhFt6sEQPt0RRGuK4rNMTg",
"ArchiveDescription":"/home/home_upload_folder_nosymlink.tar.gz",
"CreationDate":"2013-02-12T21:19:10Z",
"Size":853,
"SHA256TreeHash":"259d74a6064e73b97840d8146aec588ce5775a41bacff5c1192b65adfefad155"
},

**Comment by carlossg** [comment]
you're missing the last parameter `download vault_name archiveId output_file`

**Comment by rsereda** [comment]
I resolve my issue.

but have same information for you. May it will be inerested.

I upload my file to glacier with this command 
java -jar glacier-1.1-SNAPSHOT-jar-with-dependencies.jar  upload MWP /home/home_backup.tar.gz

Where /home/home_backup.tar.gz foolpath to file. 
You tool succses upload file to glacier but no one try to dawnload this file can not be succsesful.

I discovery this problem and find that problem in "/" symbols in filename and glacier cant take you correct path to  dawnload.

I try different client application.
