### ISSUE TITLE
Unable to upload to glacier

### ISSUE THREAD

**Issue by dernasherbrezon** [carlossg/glacier-cli#26]
Getting the following exception:

```
Exception in thread "main" java.lang.RuntimeException: Error Uploading <filename> to Glacier vault <vaultname>
   at org.csanchez.aws.glacier.Glacier.upload(Glacier.java:223)
   at org.csanchez.aws.glacier.Glacier.main(Glacier.java:140)
Caused by: com.amazonaws.AmazonClientException: Unable to compute hash
   at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:86)
   at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:57)
   at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.uploadInSinglePart(ArchiveTransferManager.java:481)
   at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.upload(ArchiveTransferManager.java:251)
   at com.amazonaws.services.glacier.transfer.ArchiveTransferManager.upload(ArchiveTransferManager.java:210)
   at org.csanchez.aws.glacier.Glacier.upload(Glacier.java:220)
   ... 1 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
   at java.util.ArrayList.rangeCheck(ArrayList.java:635)
   at java.util.ArrayList.get(ArrayList.java:411)
   at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:134)
   at com.amazonaws.services.glacier.TreeHashGenerator.calculateTreeHash(TreeHashGenerator.java:84)
   ... 6 more
```

Command: `java -jar ./bin/glacier-1.1-cli.jar upload <vaultname> <filename>`

**Comment by dernasherbrezon** [comment]
It seems caused by empty file. Is it possible to generate user-friendly exception with better explanation?
